### PR TITLE
Added support for headers

### PR DESCRIPTION
**Pull request by ifranlaloe**
Dear maintainers,

I ran into a use case where I needed the headers of the message, I noticed that version 3.0.1 of the logstash-input-stomp did not support headers. So I implemented it myself. There was already a feature request to implement headers (#14). Thus I did not create a new issue.  However I did implement the feature a little bit different.

I have tested this with ActiveMQ.

Kind regards

### CODE REVIEW

**Review by wiibaa — CHANGES_REQUESTED** [review]
Thanks for your proposal.
Your proposal would create event mixing the header and message body in the same `message` field like
`{message => 'header1=value1 header2=value2 messagebody}`

As logstash event can be structured, it would be more direct to store the headers array in a new field of the event
What do you think ?

**Comment by ifranlaloe** [comment]
Dear wiibaa,

Thank your for reviewing my changes. I totally agree with you, I was already working on your proposed solution! When it's done I will check it in.

**Comment by ifranlaloe** [comment]
I have just committed my changes regarding the header mapping. Do I have to create a new pull request? (I'm also relatively new to GitHub...)

**Comment by wiibaa** [comment]
@Narfi no need to recreate a pull request, any change made to your branch is mirrored in the PR

**Comment by ifranlaloe** [comment]
Apparently this branch does not work with logstash >= 5.0.0. I have a local version that works, but it behaves different. For some reason it only sends 1 message to elasticsearch per "pull". However all of the messages on the queue are consumed.

EDIT:
The problem with only 1 message being picked off had something to do with the Postman desktop client. It adds some characters to the message that cannot be converted to a STOMP::Frame.... So I only had to change the field assignment for the headers to event.set(key, value)

**Pull request closed without merging**
