### PR TITLE
restore client as ivar + spec on registering plugin

### PR DESCRIPTION
**Pull request by wiibaa**
Fixed for #10 with minimal spec inspired from rabbitmq input
@purbon can you have a look please

### CODE REVIEW

**Comment by wiibaa** [comment]
jenkins, test it

**Comment by wiibaa** [comment]
jenkins, test it

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
@wiibaa thanks a lot for your contribution man. I wonder a couple of things, but this are more meta questions:
- What do you think about adding a client reader/writer method? this looks like it should solve the issue, right?
- Do you know why the accessor method was not working properly? at my understanding it should work, right?

/cheers
- purbon

**Comment by wiibaa** [comment]
@purbon I'm not a strong rubyist but the confusion here is that the setter was not invoked correctly as mentionned in http://stackoverflow.com/a/576439, the code would initialize a local var instead of the `@client` field
Also as the get/set mechanism is only necessary for the spec I'm not in favor of adding it if there is another way to mock the client, that is currently possible by mocking the **new_client** method as I did in the spec

**Comment by purbon** [comment]
@wiibaa oh ya! good catch, good point.

re: mocking, well I tend to avoid having a ton of class variables, shared state, as they are always issues hiding underneath. Although for now this makes the job, so i'm good for it.

LGTM

**Comment by purbon** [comment]
@wiibaa can you raise the version, and add the changes to the changelog? then I'm good merging and releasing a new version.

Thanks a lot for your time and contribution.

**Comment by wiibaa** [comment]
@purbon forgot to ping you after my commit

**Comment by vigne** [comment]
Hello,

I was wondering when version 2.0.3 is going to be released, as this will include this patch, right?
Till then is there an other way I can get the next-version besides cloning the git and using --pluginpath?

Cheers,
Ralph

**Pull request closed without merging**
